boostxyz/boost-protocol

packages/evm/contracts/budgets/AManagedBudget.sol, packages/evm/contracts/budgets/ManagedBudget.sol, packages/evm/test/budgets/ManagedBudget.t.sol, turbo.json
- Implement `ManagedBudget` contract based on `SimpleBudget`
- `reclaim` is only available to ADMIN | owner
- `disburse` is available to ADMIN | MANAGER | owner
- `setAuthorized` is available to ADMIN | owner
- `grantRoles` is available to ADMIN | owner
- `revokeRoles` is available to ADMIN | owner
- Implement `ManagedBudget.t.sol` unit tests for core `SimpleBudget` operations
fix BOOST-4439
=> [BOOST-4438] ManagedBudget Contract

packages/evm/contracts/incentives/ERC20VariableIncentive.sol, packages/evm/test/incentives/ERC20VariableIncentive.t.sol
This implements a new incentive type that allows the amount claimed to be controlled based on the signature that's passed in. If the reward is set to 0 then the amount passed in will be used as the reward amount, if the reward is set in the contract then the amount passed in will be used as a value-scalar. It's assumed amounts passed in will be Eth denominated (18 place WAD).
=> [BOOST-4506] feat(evm):  signature based incentives

packages/sdk/package.json, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/utils.test.ts, packages/sdk/vite.config.js, packages/signatures/build.js, packages/signatures/manifests/events.json, packages/signatures/manifests/functions.json, packages/signatures/package.json, pnpm-lock.yaml, turbo.json
- create `@boostxyz/signatures` with simple manifests of known function/event signatures
- at build time, generate their selectors and abi items
- in event action validation, accept `GetLogsParams` and an optional `knownEvents` parameter that can be used instead of `@boostxyz/signatures/events` in case there's an adhoc custom event that isn't yet in the `@boostxyz/signatures` manifests
TODO
- typed errors
- tests
=> [BOOST-4580] Event Action Validation

packages/evm/contracts/BoostCore.sol
This facilitates autoclaims
Still needs to be E2E tested, just wanted to get it in here
merge after #41
=> feat(evm): add delegated claims interface

packages/evm/contracts/shared/BoostError.sol, packages/evm/contracts/validators/SignerValidator.sol, packages/evm/test/validators/SignerValidator.t.sol, packages/sdk/src/Incentives/AllowListIncentive.test.ts, packages/sdk/src/Incentives/CGDAIncentive.test.ts, packages/sdk/src/Incentives/ERC1155Incentive.test.ts, packages/sdk/src/Incentives/ERC20Incentive.test.ts, packages/sdk/src/Incentives/PointsIncentive.test.ts, packages/sdk/src/Validators/SignerValidator.test.ts
This bitmap allows a single signature to allow the claiming of up to 8
incentives. We can enable more claims, it's just a question of utilizing
more storage in exchange for more possible incentives supported in a
given boost.
merge after #42
=> feat(evm): allow SignerValidator to track up to 8 incentives per Boost

packages/evm/contracts/validators/ASignerValidator.sol, packages/evm/contracts/validators/SignerValidator.sol, packages/evm/test/validators/SignerValidator.t.sol, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/BoostCore.ts, packages/sdk/src/Incentives/AllowListIncentive.test.ts, packages/sdk/src/Validators/SignerValidator.test.ts, packages/sdk/src/Validators/SignerValidator.ts, packages/sdk/src/utils.ts, packages/sdk/test/helpers.ts
This function call is stateful and an attacker could block others'
claims by calling this maliciously
merge after #44
=> [Boost-4578] Lock down 'validate` SignerValidator access

packages/evm/test/validators/SignerValidator.t.sol
These fuzz tests cover signature spoofing and also sets of inputs
that should work validate successfully.
We could go in harder on the signature spoofing if we wanted to by
constraining stack parameters and fuzzing on claimData though.
merge after #45
=> test(evm): Add fuzz tests for SignerValidator

packages/evm/contracts/BoostCore.sol, packages/evm/contracts/incentives/AAllowListIncentive.sol, packages/evm/contracts/incentives/ACGDAIncentive.sol, packages/evm/contracts/incentives/AERC1155Incentive.sol, packages/evm/contracts/incentives/AERC20Incentive.sol, packages/evm/contracts/incentives/APointsIncentive.sol, packages/evm/contracts/incentives/ERC20VariableIncentive.sol, packages/evm/contracts/incentives/Incentive.sol, packages/evm/test/BoostRegistry.t.sol, packages/evm/test/budgets/ManagedBudget.t.sol, packages/evm/test/incentives/AllowListIncentive.t.sol, packages/evm/test/incentives/CGDAIncentive.t.sol, packages/evm/test/incentives/ERC1155Incentive.t.sol, packages/evm/test/incentives/ERC20Incentive.t.sol, packages/evm/test/incentives/ERC20VariableIncentive.t.sol, packages/evm/test/incentives/PointsIncentive.t.sol
incentive claim interfaces should contain the claimTarget address as a
parameter since it's more secure and means we have to decode one less
abi bytestring
=> chore(evm): refactor Incentive `claim` interface

packages/evm/contracts/budgets/AManagedBudget.sol, packages/evm/contracts/budgets/ASimpleBudget.sol, packages/evm/contracts/budgets/AVestingBudget.sol, packages/evm/contracts/budgets/Budget.sol, packages/evm/contracts/incentives/AAllowListIncentive.sol, packages/evm/contracts/incentives/ACGDAIncentive.sol, packages/evm/contracts/incentives/AERC1155Incentive.sol, packages/evm/contracts/incentives/AERC20Incentive.sol, packages/evm/contracts/incentives/APointsIncentive.sol, packages/evm/contracts/incentives/ERC20VariableIncentive.sol, packages/evm/contracts/incentives/Incentive.sol, packages/evm/test/budgets/ManagedBudget.t.sol, packages/evm/test/budgets/SimpleBudget.t.sol, packages/evm/test/budgets/VestingBudget.t.sol, packages/evm/test/incentives/AllowListIncentive.t.sol, packages/evm/test/incentives/CGDAIncentive.t.sol, packages/evm/test/incentives/ERC1155Incentive.t.sol, packages/evm/test/incentives/ERC20Incentive.t.sol, packages/evm/test/incentives/ERC20VariableIncentive.t.sol, packages/evm/test/incentives/PointsIncentive.t.sol, packages/sdk/src/Budgets/SimpleBudget.ts, packages/sdk/src/Budgets/VestingBudget.ts, packages/sdk/src/Incentives/CGDAIncentive.ts, packages/sdk/src/Incentives/ERC1155Incentive.ts, packages/sdk/src/Incentives/ERC20Incentive.ts
`reclaim` can be conflated with `claim`, so `clawback` is a more distinctly
helpful name.
=> [BOOST-4637] rename `reclaim` to `clawback`

packages/evm/test/budgets/VestingBudget.t.sol
~~Up to 92%. Ran into the same issues with the ASimpleBudget.~~
Up to 98%. Only line not covered is `reconcile` function. I was able to test unsupported asset type on this one since ERC1155 is not supported in the vesting budget.
- Reconcile is tested, but not being detected in coverage
- ~~Not able to test unsupported asset type. (See https://github.com/rabbitholegg/boost-protocol/pull/70)~~
=> [BOOST-4615]: test(evm): Increase VestingBudget Coverage 

packages/evm/test/budgets/SimpleBudget.t.sol
I was only able to get the coverage up to 94%.
There is one line which is the `reconcile` function. This simple function just returns `0`, and is present in the test cases. However, due to a bug? with the coverage tool, it does not get considered as covered. You need to do something like this for it to be considered covered.
```
function reconcile(bytes calldata) external virtual override returns (uint256) {
uint256 zero = 0;
return zero;
}
```
https://github.com/rabbitholegg/boost-protocol/blob/f02171710699539c1ae6382081b8d3b0ffe0ede1/packages/evm/contracts/budgets/ASimpleBudget.sol#L222-L224
The rest of the uncovered lines are for unsupported asset types. Im not able to figure out a way trigger these conditions. I feel like I have tried everything, including manipulating the raw …
=> [BOOST-4614]: test(evm): Increase SimpleBudget Coverage

packages/evm/test/BoostCore.t.sol
There are still 2 lines that don't have coverage but one is unreachable and the other is unlikely. Will add in subsequant but it'll require mocks so I just want to get the bulk of them in especially since this adds the main testing around the claim flow in the core unit tests. Want a `SignerValidator` test in the core unit tests added as well.
=> [BOOST-4611] test(evm): increase boost core coverage

.changeset/hungry-beds-peel.md, packages/sdk/src/Actions/Action.ts, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/errors.ts, packages/sdk/src/utils.ts, packages/sdk/test/MockERC721.ts, packages/sdk/test/helpers.ts, packages/sdk/test/viem.ts
- offer alternate `EventActionPayloadSimple` where you can pass `actionSteps: ActionStep[]` instead of `{ actionStepOne: ActionStep, ...etc }`
- for all read ops, `getActionStep`, `getActionSteps`, etc. dedupe reused action steps, so while there are technically always 4 on the contract, the sdk will know which ones are unique.
- basic integration tests, can reference for example development
- typed errors
- fix validation for address equality
=> [BOOST-4693] Event Action Beautification / Hardening

.changeset/empty-feet-cheat.md, packages/sdk/package.json, packages/sdk/vite.config.js
configure sdk vite to generate sourcemaps
configure sdk/package.json to include `src` in package artifact so as to not break the "sources" field in es module sourcemaps
fix #91 
💔 Thank you!
yw
=> fix(sdk): build, publish sourcemaps

packages/sdk/src/Actions/EventAction.ts
Fixes a bug in `isActionStepValid` where it would always return true due to an un-awaited promise being used in a boolean conditional.
💔 Thank you!
=> [ADHOC] fix(EventAction): await validation in log criteria check

packages/evm/contracts/actions/AEventAction.sol, packages/evm/test/actions/EventAction.t.sol, packages/sdk/src/Actions/Action.test.ts, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/utils.ts, packages/sdk/test/helpers.ts, packages/signatures/build.js, packages/signatures/manifests/events.json, packages/signatures/manifests/functions.json
resolves BOOST-4706: Add chainId to event action parameters
resolves BOOST-4707: support chainid in EventAction
chainId is needed to disambiguate the location of the address
=> [BOOST-4692] Support chainId in EventAction

.changeset/wicked-feet-tap.md, packages/sdk/test/delegate-action.test.ts, packages/signatures/manifests/events.json
- delegate to any address (tally/agora)
- uses a static reward incentive structure
- keys off the `DelegateChanged` event, specifically the `toDelegate` parameter which is topic 3.
Notes:
- You can technically delegate to an address without actually holding the token, so using a fixed reward structure here may not be the best way. Might be better to give out rewards based on how many tokens they delegate, and for how long.
=> [BOOST-4686] test delegation to a specific delegate address

packages/sdk/src/Actions/Action.test.ts, packages/sdk/src/Actions/ContractAction.test.ts, packages/sdk/src/Actions/ERC721MintAction.test.ts, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/AllowLists/AllowList.test.ts, packages/sdk/src/AllowLists/SimpleAllowList.test.ts, packages/sdk/src/AllowLists/SimpleDenyList.test.ts, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/Incentives/AllowListIncentive.test.ts, packages/sdk/src/Incentives/CGDAIncentive.test.ts, packages/sdk/src/Incentives/ERC20Incentive.test.ts, packages/sdk/src/Incentives/PointsIncentive.test.ts, packages/sdk/src/Validators/SignerValidator.test.ts, packages/sdk/test/delegate-action.test.ts, packages/sdk/test/helpers.ts, packages/sdk/test/zora-fork-mint.test.ts
When writing test/validation cases, you had to access base contract implementations like `createBoost({ allowList: new fixtures.bases.SimpleAllowList(options, {}) })` which is the more verbose, discouraged way to instantiate components and may be confusing to consumers reading the tests/examples as a reference.
support `createBoost({ allowList: core.SimpleAllowList({}) })` API in test cases so examples are 1:1 with real world production usage
💔 Thank you!
=> [ADHOC] refactor(sdk,tests): refactor testing api to support same api as non-test usage

.changeset/chatty-eagles-collect.md, packages/sdk/src/Actions/Action.test.ts, packages/sdk/src/Actions/ContractAction.test.ts, packages/sdk/src/Actions/ERC721MintAction.test.ts, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/AllowLists/AllowList.test.ts, packages/sdk/src/AllowLists/AllowList.ts, packages/sdk/src/AllowLists/OpenAllowList.test.ts, packages/sdk/src/AllowLists/OpenAllowList.ts, packages/sdk/src/AllowLists/SimpleAllowList.test.ts, packages/sdk/src/AllowLists/SimpleDenyList.test.ts, packages/sdk/src/AllowLists/SimpleDenyList.ts, packages/sdk/src/BoostCore.ts, packages/sdk/src/Deployable/DeployableTarget.ts, packages/sdk/src/Incentives/AllowListIncentive.test.ts, packages/sdk/src/Validators/SignerValidator.test.ts, packages/sdk/test/helpers.ts
`createBoost({ allowList: core.OpenAllowList() })`
- `OpenAllowList` extends `SimpleDenyList`
- init payload sets owner to `0x`, `denied=[]`
- tests
- accoutrements 
💔 Thank you!
=> [ADHOC] feat(sdk): add OpenAllowList as zero config extension of SimpleDenyList

.gitignore, packages/cli/tsconfig.json, packages/sdk/package.json, packages/sdk/tsconfig.build.json
The default tsconfig file is usually used in conjunction
with an IDE and a separate build config is used for the
build pipeline. The impetus for this is working with
monorepo package imports in test files was opaque before and
now they are transparent in the IDE.
=> [ADHOC] chore(sdk): enable tsconfig for test files

.changeset/silver-bobcats-switch.md, packages/sdk/src/Budgets/ManagedBudget.test.ts, packages/sdk/src/Budgets/ManagedBudget.ts, packages/sdk/src/Budgets/SimpleBudget.test.ts, packages/sdk/src/Budgets/SimpleBudget.ts, packages/sdk/src/Budgets/VestingBudget.test.ts, packages/sdk/src/Budgets/VestingBudget.ts
On all methods for the various Budget Accounts in the SDK, we should make the `asset` param default to the zero address. This allows the SDK functions to fetch the native tokens without having to explicitly pass in the zero address.
Addresses this issue: https://github.com/rabbitholegg/boost-protocol/issues/116
=> [BOOST-4772] Refactor Budget Methods

.changeset/great-files-cheer.md, biome.json, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts
This allows for cleaner separations of concerns by separating the pre-gathered log params out from the getter/setter params for smart contract functions. However, the shape is not determined based on class state (ie action type), so a user can still potentially input incorrect validation params and only receive an error at runtime
=> [BOOST-4752] fix(sdk): split EventAction input params into two objects

.changeset/great-bulldogs-buy.md, .changeset/tiny-baboons-buy.md, package.json, packages/evm/contracts/actions/AEventAction.sol, packages/evm/hardhat_build.config.cjs, packages/evm/package.json, packages/sdk/hardhat.config.cjs, packages/sdk/package.json, packages/sdk/src/Actions/Action.test.ts, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/errors.ts, packages/sdk/test/helpers.ts, packages/signatures/manifests/events.json, pnpm-lock.yaml
This PR implements Regex event action support and also cleans up argument
handling. Now that we are strictly parsing logs with event ABIs, we are able
to support non-indexed params.
resolves BOOST-4752
resolves BOOST-4754
=> [BOOST-4710] Add regex event action

packages/evm/contracts/incentives/CGDAIncentive.sol, packages/evm/test/incentives/CGDAIncentive.t.sol, packages/evm/test/incentives/ERC20VariableIncentive.t.sol
While other areas in the stack could potentially prevent this issue,
including the SignerValidator, which tracks claim increments,
this contract was designed to limit claims to 1 for each address.
=> [BOOST-4729] fix(evm): make mulitiple CGDA claims impossible

.changeset/red-stingrays-greet.md, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts, packages/signatures/build.js
action step signatures were changed to bytes32, this change pads the function signature generation at build time
💔 Thank you!
=> [ADHOC] fix(signatures): pad function selectors to 32 bytes

packages/evm/contracts/BoostCore.sol, packages/evm/test/BoostCore.t.sol, packages/evm/test/incentives/ERC20VariableIncentive.t.sol
We should prevent deployment of unclaimable boosts by reverting if no
validator is supplied to `createBoost`
=> [BOOST-4730] fix(evm): revert createBoost if no Validator

packages/evm/contracts/validators/SignerValidator.sol, packages/evm/test/validators/SignerValidator.t.sol
We were only shifting the trailing bits off the stack but not masking
the leading bits, leading to a situation where incentives could not be
claimed out of order.
This is fixed by and-masking against 1 after shifting the incentive index to
the least significant bit.
=> [BOOST-4785] Correctly masking leading bits for incentives in SignerValidator

.changeset/fuzzy-walls-eat.md, examples/ens-register/src/ens-register.test.ts, examples/ens-register/vitest.config.ts, packages/signatures/manifests/functions.json, test/src/viem.ts
- changes ENS test to use register function selector instead of using the `NameRegistered` event. The event used a bytes32 value for the address, and bytes comparison is not allowed on indexed event args.
- updates test to work in new examples directory.
- adds register function selector to signatures package
- adds sepolia to wagmi config in `/test/src/viem.ts`
=> [ADHOC]: update ENS tests to use register function selector

packages/sdk/package.json, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/tsconfig.json, pnpm-lock.yaml
The refactor to utilize decoded args broke uint equality comparisons and
this fixes it. I've also taken this opportunity to add unit tests to
catch regressions for these comparisons in CI and during other work,
since writing e2e cases is much more arduous and that focus prevented us
from covering against potential regressions here.
resolves #151
=> [BOOST-4790] fix UINT field comparisons

packages/sdk/hardhat.config.cjs
If there is a valid `VITE_ALCHEMY_API_KEY`, then `pnpm test` may not run
Now that the examples exist outside of the sdk package, we can simplify the hardhat config
=> [ADHOC] chore: simplify hardhat config

examples/zora-mint/src/zora-mint.test.ts, packages/evm/contracts/BoostCore.sol, packages/evm/test/e2e/EndToEndBasic.t.sol
Allowlists were only checked in the AllowList incentives, but this
change enforces allowlists for all claims. E2E tests have been added to
validate enforcement and also ensure that no tests pass because of some
other authentication failure.
=> [BOOST-4747] fix(evm): check claims against allowlist in BoostCore

packages/sdk/src/Actions/ContractAction.ts, packages/sdk/src/Actions/ERC721MintAction.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/AllowLists/SimpleAllowList.ts, packages/sdk/src/AllowLists/SimpleDenyList.ts, packages/sdk/src/Boost.ts, packages/sdk/src/BoostCore.ts, packages/sdk/src/BoostRegistry.ts, packages/sdk/src/Budgets/ManagedBudget.ts, packages/sdk/src/Budgets/VestingBudget.ts, packages/sdk/src/Deployable/Contract.ts, packages/sdk/src/Deployable/Deployable.ts, packages/sdk/src/Deployable/DeployableTarget.ts, packages/sdk/src/Deployable/DeployableTargetWithRBAC.ts, packages/sdk/src/Incentives/AllowListIncentive.ts, packages/sdk/src/Incentives/CGDAIncentive.ts, packages/sdk/src/Incentives/ERC1155Incentive.ts, packages/sdk/src/Incentives/ERC20Incentive.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.ts, packages/sdk/src/Incentives/Incentive.ts, packages/sdk/src/Incentives/PointsIncentive.ts, packages/sdk/src/Validators/SignerValidator.ts, packages/sdk/src/Validators/Validator.ts, packages/sdk/src/claiming.ts, packages/sdk/src/transfers.ts, packages/sdk/src/utils.ts
- a lot of typedoc return types were either missing or incorrect, making the generated docs confusing
- in typedocs, remove the `ReadParams/WriteParams<typeof abi, 'function'>` generics to get rid of the entire abi being inlined in the typedoc. The interfaces are still correct in type definitions, but this should greatly reduce noise in the docs site
💔 Thank you!
=> [ADHOC] chore(sdk): correct all typedoc return types

packages/evm/contracts/incentives/AAllowListIncentive.sol, packages/evm/contracts/incentives/ACGDAIncentive.sol, packages/evm/contracts/incentives/AERC1155Incentive.sol, packages/evm/contracts/incentives/AERC20Incentive.sol, packages/evm/contracts/incentives/AERC20VariableIncentive.sol, packages/evm/contracts/incentives/AIncentive.sol, packages/evm/contracts/incentives/APointsIncentive.sol, packages/evm/contracts/incentives/ERC1155Incentive.sol, packages/evm/script/solidity/ComponentInterface.s.sol, packages/evm/test/incentives/ERC1155Incentive.t.sol, packages/sdk/src/Incentives/Incentive.ts
Claimants can claim 1 ERC 1155 per transaction. Transactions are
validated offchain, but to ensure a unique signanature and claim
attempt, transaction hashes are passed in as part of the claim payload
and stored onchain. As a basic validation with `isClaimable`, the same
transaction hash cannot be claimed against, irrespective of the claim
target
=> [BOOST-4736] fix(evm): enable multiple claims by an address for ERC1155Incentives

.changeset/nasty-planes-remain.md, examples/zora-mint/src/zora-mint.test.ts, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/errors.ts
There are several changes in this PR:
- Uses the tx hash to fetch logs for event validation
- Moves the onchain data fetching from `isActionEventValid` and `isActionFunctionValid` into the parent `isActionStepValid` function
- On event validation, we check against all logs rather than the first match -- this allows us to validate if the tx has multiple logs that are the same (e.g. multiple transfer events on a Uniswap tx)
=> [BOOST-4797] feat(action-step): handle data fetching at action step level

.changeset/plenty-ligers-notice.md, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/BoostCore.ts
add `getClaimFromTransaction` to BoostCore
tests
fix #139 
💔 Thank you!
=> [BOOST-4786] feat(sdk): add  `getClaimFromTransaction` method to BoostCore

examples/zora-mint/src/zora-mint.test.ts, packages/evm/contracts/budgets/ABudget.sol, packages/evm/contracts/incentives/CGDAIncentive.sol, packages/evm/contracts/incentives/ERC1155Incentive.sol, packages/evm/contracts/incentives/ERC20Incentive.sol, packages/evm/contracts/incentives/ERC20VariableIncentive.sol, packages/evm/contracts/shared/RBAC.sol, packages/evm/script/solidity/ComponentInterface.s.sol, packages/evm/script/solidity/Deploy_Modules.s.sol, packages/evm/script/solidity/Util.s.sol, packages/evm/test/BoostCore.t.sol, packages/evm/test/budgets/ManagedBudget.t.sol, packages/evm/test/e2e/EndToEndBasic.t.sol, packages/evm/test/e2e/EndToEndSignerValidator.t.sol, packages/evm/test/incentives/CGDAIncentive.t.sol, packages/evm/test/incentives/ERC1155Incentive.t.sol, packages/evm/test/incentives/ERC20Incentive.t.sol, packages/evm/test/incentives/ERC20VariableIncentive.t.sol, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/Incentives/CGDAIncentive.test.ts, packages/sdk/src/Incentives/CGDAIncentive.ts, packages/sdk/src/Incentives/ERC20Incentive.test.ts, packages/sdk/src/Incentives/ERC20Incentive.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.test.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.ts, packages/sdk/src/Incentives/Incentive.test.ts
This change enables budgets to reclaim funds from incentives they have seeded.
Transfers are not safety-checked because this is effectively a reverse transfer.
In other words, it is assumed that a budget that deployed those funds can
safely accept them without loss.
Additionally, this function ensures funds can only be returned to the budget.
This design decision allows for Managers and not just owners of budgets to
call this function.
This is all implemented on the Incentive side by utilizing `RBAC` and
auth-gating the  incentive `clawback` function on the `MANAGER_ROLE`.
BoostCore is still set as the owner so it can call the incentive `claim`
function.
=> [BOOST-4780] feat: Implement `clawBackFromIncentive`

.gitignore, packages/evm/hardhat_build.config.cjs
This change fixes some strange caching behavior with foundry. I think
foundry greedily checks this cache folder if it exists, regardless of
its config, so moving the hardhat cache should improve some foundry
performance when working locally.
=> chore(evm): move hardhat cache from `cache` to `cache_hh`

.changeset/fluffy-dolphins-dress.md, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts
We want to be able to use `anyActionParam()` when we want to define a basic action parameter that allows for easy validation. An example use case is if we want to validate that a user called a function, but don't care about any parameters
I decided against making the Criteria optional, as it does kind of make some of the type checking throughout the EventAction.ts file messy
fix #206
=> [BOOST-4831] feat: add anyActionParam

.changeset/fair-chicken-confess.md, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts
add `msgSenderClaimant` utility to event action
add tsdoc
add test
some autoformatting hath occured
💔 Thank you!
=> [ADHOC] feat(sdk,EventAction): add msgSenderClaimant utility, test

.changeset/real-planes-ring.md, packages/signatures/manifests/events.json
- add BoostCreated and BoostClaimed events to event signatures.
- add SecondaryBuy event (Zora Secondary)
💔 Thank you!
=> [ADHOC]: add BoostCreated and BoostClaimed events to signatures

.changeset/ten-horses-sleep.md, packages/sdk/src/Validators/SignerValidator.ts
Got the following error when trying to generate a signature:
```
Error: private key must be 32 bytes, hex or bigint, not string
```
This happens because the `signTypedData` expects a private key, which we cannot access. It seemed like we tried to pass in `signer.key`, but that is the public key
=> [ADHOC] Fix SignerValidator Signature

.changeset/shaggy-moose-fry.md, packages/sdk/src/Actions/EventAction.ts
We try to decode the logs in a tx, but only pass in a specific set of abi. Since most txs have a ton of other events, viem throws a `DecodeLogTopicsMismatch` error
This PR adds a filter to those logs so that we only decode logs that we care about in the action step validation and action claimant
=> [ADHOC] Fix `DecodeLogTopicsMismatch` Error

packages/evm/contracts/actions/AEventAction.sol, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts
Adds `GREATER_THAN_OR_EQUAL` and `LESS_THAN_OR_EQUAL` to `EventAction.sol` and `EventAction.ts`
This will require a redeployment
💔 Thank you!
=> [ADHOC] feat: add OR_EQUAL filters to event action

packages/evm/contracts/BoostCore.sol, packages/evm/test/BoostCore.t.sol, packages/evm/test/e2e/EndToEndBasic.t.sol, packages/evm/test/e2e/EndToEndSignerValidator.t.sol, packages/sdk/src/BoostCore.test.ts
Fix to account for per-boost protocol fees. Most likely we will not use this but better to have it and not need it etc.
This PR will be passed off to the lead auditor as well.
💔 Thank you!
=> [ADHOC] fix(evm): ensure additional protocol fees can set fees per boost

.changeset/lazy-cows-sip.md, packages/sdk/src/Budgets/ManagedBudget.ts, test/src/helpers.ts
- Deprecated `ManagedBudgetRoles` on the ManagedBudget in favour of the RBAC `Roles` enum. 
- Updates any references to `ManagedBudgetRoles` with `Roles`
=> [BOOST-4904] deprecate managedbudgetroles enum for roles

examples/zora-mint/hardhat.config.cjs
This is working for me locally but want to make sure it works on remote. We should figure out why the reset isn't working as expected anymore. I'm getting current block when this isn't set in config after their most recent update.
💔 Thank you!
=> [ADHOC] fix(zora-mint): hh block config

.changeset/real-boxes-jump.md, packages/sdk/src/Actions/ContractAction.ts, packages/sdk/src/Actions/ERC721MintAction.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/AllowLists/SimpleAllowList.ts, packages/sdk/src/AllowLists/SimpleDenyList.ts, packages/sdk/src/Auth/PassthroughAuth.ts, packages/sdk/src/BoostCore.ts, packages/sdk/src/BoostRegistry.ts, packages/sdk/src/Budgets/ManagedBudget.ts, packages/sdk/src/Budgets/VestingBudget.ts, packages/sdk/src/Deployable/DeployableTarget.ts, packages/sdk/src/Deployable/DeployableTargetWithRBAC.ts, packages/sdk/src/Incentives/AllowListIncentive.ts, packages/sdk/src/Incentives/CGDAIncentive.ts, packages/sdk/src/Incentives/ERC1155Incentive.ts, packages/sdk/src/Incentives/ERC20Incentive.ts, packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.ts, packages/sdk/src/Incentives/PointsIncentive.ts, packages/sdk/src/Validators/LimitedSignerValidator.ts, packages/sdk/src/Validators/SignerValidator.ts, packages/sdk/src/utils.ts, test/src/MockERC1155.ts, test/src/MockERC20.ts, test/src/MockERC721.ts, test/src/MockPoints.ts
- use SimulateContractParameters instead of generic write params, it's more technically correct, as simulate accepts more state overrides.
- remove abi and names from generic read/write params interfaces, it really speeds up ts server for local development, makes tsdoc much more legible, and still satisfactory as far as interfaces go
💔 Thank you!
=> [ADHOC] refactor(sdk): use SimulateContractParameters instead of WriteContractParameters

.changeset/real-suns-explode.md, packages/cli/src/commands/seed.ts
- Make the Validator field optional in the seed configuration. If omitted, the default validator will be used.
- Make the Allowlist field optional in the seed configuration. If omitted, an open allowlist will be used.
- Fix type issues
- Remove unnecessary type assertions
These changes simplify the seed configuration by allowing users to omit the validator and allowlist settings when default behavior is desired.
💔 Thank you!
=> [ADHOC] feat(cli): allow Validator to be optional in seed

packages/evm/contracts/BoostCore.sol, packages/evm/script/solidity/Deploy.s.sol, packages/evm/test/BoostCore.t.sol, packages/evm/test/e2e/EndToEndBasic.t.sol, packages/evm/test/e2e/EndToEndSignerValidator.t.sol
Adds an owner param to the BoostCore constructor
=> [ADHOC] fix: add owner param to BoostCore constructor

.changeset/short-spies-kiss.md, packages/sdk/src/Actions/Action.ts, packages/sdk/src/AllowLists/AllowList.ts, packages/sdk/src/BoostCore.ts, packages/sdk/src/Budgets/Budget.ts, packages/sdk/src/Incentives/Incentive.ts, packages/sdk/src/Validators/Validator.ts
- fixes a bug were `core.getBoost` would error when targetting different chains using params.
` const boost = await core.getBoost(2n, { chainId: 84532 });`
Fix was to pass the params that are input to the getBoost method to internal contract reads.
💔 Thank you!
=> [BOOST-5051] fix issues with `core.getBoost`

.changeset/quick-berries-decide.md, packages/sdk/src/Incentives/AllowListIncentive.test.ts, packages/sdk/src/Incentives/AllowListIncentive.ts, packages/sdk/src/Incentives/CGDAIncentive.test.ts, packages/sdk/src/Incentives/CGDAIncentive.ts, packages/sdk/src/Incentives/ERC1155Incentive.ts, packages/sdk/src/Incentives/ERC20Incentive.test.ts, packages/sdk/src/Incentives/ERC20Incentive.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.test.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.ts, packages/sdk/src/Incentives/PointsIncentive.test.ts, packages/sdk/src/Incentives/PointsIncentive.ts
- fixes issue with `incentive.isClaimable()` throwing an error because of misconfigured arguments
- adds comprehensive tests for each incentive type
Linear Ticket: https://linear.app/rh-app/issue/BOOST-4992/fix-incentiveisclaimable-throws-error
Related Github Issue: https://github.com/boostxyz/boost-protocol/issues/278
💔 Thank you!
=> [BOOST-4992] fix `incentive.isClaimable()` throws error

.changeset/spicy-monkeys-tease.md, packages/sdk/src/Deployable/DeployableTargetWithRBAC.test.ts, packages/sdk/src/Deployable/DeployableTargetWithRBAC.ts
- adds the following methods to `DeployableTargetWithRBAC`
- `transferOwnership`
- `renounceOwnership`
- `requestOwnershipHandover`
- `completeOwnershipHandover`
- `cancelOwnershipHandover`
- `ownershipHandoverExpiresAt`
- `renounceRoles`
- adds tests for each new method to ensure they are working as expected
💔 Thank you!
=> [BOOST-4989] add public methods from `Ownable` to `DeployableTargetWithRBAC`

.changeset/shiny-pandas-rush.md, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts
Having a `notBeforeBlockNumber` param previously returned a boolean. We only care about returning false, otherwise continue validating the action step
=> [ADHOC] Fix block number validation

packages/evm/contracts/incentives/AERC20PeggedIncentive.sol, packages/evm/contracts/incentives/ERC20PeggedIncentive.sol, packages/evm/script/solidity/ComponentInterface.s.sol, packages/evm/script/solidity/Deploy_Modules.s.sol, packages/evm/test/incentives/ERC20PeggedIncentive.t.sol, packages/sdk/src/BoostCore.ts, packages/sdk/src/Incentives/ERC20PeggedIncentive.ts, packages/sdk/src/Incentives/Incentive.ts, packages/sdk/src/index.ts
This PR adds a new incentive type. It's almost like a mix of the variable incentive and the standard erc20 incentive. I stripped out raffle functionality.
Limit for this incentive is the _total spend_ similar to a variable incentive.
The claim amount will always be the signed amount so the signed amount should be the reward amount in the peg token converted into the reward token.
Reward amount should be denominated in peg token and then signed amount should be the spot price conversion between reward token and peg token such that the **signed amount in reward token** = **reward amount in pegged token**. This means in the signature endpoint …
=> [BOOST-5055] feat(evm/sdk): fork existing erc20 incentive and add peg token

packages/evm/contracts/BoostCore.sol, packages/evm/contracts/actions/ERC721MintAction.sol, packages/evm/contracts/shared/BoostLib.sol, packages/evm/contracts/shared/IProtocolFeeModule.sol, packages/evm/contracts/shared/Mocks.sol, packages/evm/contracts/validators/AValidator.sol, packages/evm/contracts/validators/LimitedSignerValidator.sol, packages/evm/contracts/validators/SignerValidator.sol, packages/evm/test/BoostCore.t.sol, packages/evm/test/e2e/EndToEndBasic.t.sol, packages/evm/test/e2e/EndToEndSignerValidator.t.sol, packages/evm/test/shared/Mocks.t.sol
This makes two major changes:
- Adds protocol fee module hooks into core
- Makes validators payable so that we can pass through native tokens for fees as needed.
This is still in draft as I need to pad out test coverage which means we need a mock testing version of this module. I'm going to add that ASAP but this should be all of the actual contract changes. The way I set it requires minimal changes to the existing tests but I'm open to the idea of passing the module through on construction.
Also worth looking at the note in the interface to weigh in on approach there/where the struct should live.
=> [BOOST-5072] feat(evm): add fee module to core and pass value to validators

.changeset/slow-apricots-heal.md, packages/sdk/src/Incentives/ERC20PeggedIncentive.ts
Returns abi encoded value for ERC20PeggedIncentive instead of the zeroHash
=> [ADHOC] Build Claim Data for ERC20PeggedIncentive

.changeset/five-numbers-hide.md, packages/evm/contracts/BoostCore.sol, packages/evm/test/BoostCore.t.sol
There is an issue with the way we were detecting the initial and final balance used to determine the protocol fee amount. We were checking the boostCore balance in `_getAssetBalance` instead of the balance of the incentive. This caused the protocolFeeAmount to always be zero, and no protocol fees are ever sent to the fee recipient.
The fix here is to check the incentive balance for changes instead of boostCore.
=> [BOOST-5104] fix issue with protocol fee transfer

packages/evm/test/BoostCore.t.sol
Just wanted to ensure that fee calculations behave as expected when
additional fees are added to boost.
This doesn't increase the significantly long time it takes this fuzz
test to run. It's just another param that gets fuzzed.
=> [ADHOC] test(evm): add fuzz testing for additional fees

.changeset/strange-parents-lay.md, packages/evm/contracts/incentives/CGDAIncentive.sol, packages/evm/contracts/incentives/ERC1155Incentive.sol, packages/evm/contracts/incentives/ERC20Incentive.sol, packages/evm/contracts/incentives/ERC20PeggedIncentive.sol, packages/evm/contracts/incentives/ERC20PeggedVariableCriteriaIncentive.sol, packages/evm/contracts/incentives/ERC20VariableIncentive.sol, packages/evm/test/BoostCore.t.sol, packages/evm/test/e2e/EndToEndBasic.t.sol, packages/evm/test/incentives/CGDAIncentive.t.sol, packages/evm/test/incentives/ERC1155Incentive.t.sol, packages/evm/test/incentives/ERC20VariableIncentive.t.sol, packages/sdk/src/Incentives/CGDAIncentive.ts, packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.test.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.ts
We had a bunch of different logic for authing clawback on incentives.
This standardizes it to allow for the optional designation of a manager
outside of BoostCore, which always is configured as the owner via
the boost creation flow.
=> [ADHOC] fix(evm): incentive clawback perm fix

biome.json
- add sdk/cache to ignored files in biome config. we were seeing many errors appear from the cache as shown in the image below.
=> [ADHOC] chore: add sdk/cache to ignored paths in biome.json

.github/workflows/danger.yaml, dangerfile.ts
I can modify the PR title and description and danger will re-run. This still also includes all the default `on: pull_request:` events as well.
=> [ADHOC] chore(ci): make danger re-run on PR edits

.changeset/few-pugs-behave.md, packages/sdk/src/BoostCore.ts, turbo.json
Deploying a budget from `core` should auto-add that core instance as a
manager, or the user will get an error if they don't add it themselves.
This might be addressed in boostxyz/boost, but it's probably better if
this affordance lives in the sdk.
=> [ADHOC] fix(sdk): auto-add boostcore as ManagedBudget manager

.changeset/itchy-news-exercise.md, packages/evm/contracts/actions/AEventAction.sol, packages/sdk/README.md, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/errors.ts
1. **Nested Tuple Support:**  
- Added logic for *bit-packed* `fieldIndex` when the `fieldType` is `TUPLE`.  
- Each sub-index is stored in a 6-bit segment, so we can drill through up to five nesting levels.  
- A value of **63** (the maximum 6-bit integer) acts as a terminator indicating “no further indexes.”
2. **Final Primitive Resolution:**  
- When the parser encounters a tuple in the ABI, it recursively unpacks each sub-index to select the correct sub-component.  
- At the last nested component (a leaf), we derive the real `PrimitiveType` (e.g., `ADDRESS`, `UINT`, `BYTES`, `STRING`) by inspecting the ABI definition.
3. **Refactored Parse …
=> [BOOST-5131] feat: tuple support for eventaction

.changeset/mighty-snakes-leave.md, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/BoostCore.ts
- adds `getIncentiveFeesInfo` method to sdk
- ~~adds enum for AssetType~~ 
- add test for functionality
=> [BOOST-5140] add `getIncentiveFeesInfo` sdk method to boostcore

.changeset/bright-kids-pay.md, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts
- adds a helper to re-organize event args to match the structure of the abi. 
- added multiple tests to ensure the correct order and that it will not effect events that do not have indexed params.
=> [BOOST-5108] fix order of indexed params in events to match abi

.changeset/silly-carpets-jog.md, packages/sdk/src/Incentives/ERC20PeggedIncentive.ts
Add decodeClaimData to ERC20PeggedIncentive
=> [ADHOC] Add decodeClaimData to ERC20PeggedIncentive

.changeset/cold-days-yell.md, packages/sdk/src/Actions/EventAction.ts
- removes event action validation from `decodeTransferLogs` method
- applies `decodeTransferLogs` in the `deriveActionClaimantFromTransaction` method
- fixes lint warning in `decodeAndReorderLogArgs` *Do not use new Array(singleArgument)*
- tested locally
=> [BOOST-5197] update transfer signature logic to allow for deriving claimant

.changeset/cool-turkeys-punch.md, packages/sdk/src/Actions/EventAction.ts
- fixes issue with address "undefined" in claimant address comparison
=> [BOOST-5209] fix: signature event issue address undefined is invalid

.changeset/breezy-jokes-judge.md, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts
The usage of terminators was confusing for integrators so now we automatically add a terminator so users of the SDK don't need to understand how the field index packing works as well. Now when an array of less than five is packed into the packing function we just automatically append a terminator so that the underlying data structure doesn't need to be understood at all at the application level.
💔 Thank you!
=> [BOOST-5221] feat(sdk): update tuple support helpers to add terminators

packages/evm/contracts/actions/AEventAction.sol, packages/sdk/src/Actions/EventAction.ts
Fairly straightforward. Adds the primitive type into the `EventAction` and then makes the corresponding changes in the SDK. We're also going to need to make changes in the application to handle int values on ABIs. Another thing to consider is that `int`/`uint` values less than 256 should also probably be supported. This only gets gnarly when it's a uint value smaller than `bigInt` which I believe is around uint64? 
💔 Thank you!
=> [BOOST-5215] feat(evm): uint vs int handling in event action

.changeset/smart-falcons-joke.md, packages/sdk/src/Actions/EventAction.ts
- uses a deepclone of the Transfer abi to prevent upstream mutations
https://developer.mozilla.org/en-US/docs/Web/API/Window/structuredClone
=> [ADHOC] fix: prevent transfer abi mutation

.changeset/proud-pianos-pretend.md, packages/sdk/src/Actions/EventAction.ts
- allows use of a 4-byte function selector as a signature when setting up action steps in boost creation using SDK.
- all signatures will be left padded to 32-bytes
- tested locally in SDK playground using pnpm link
https://linear.app/rh-app/issue/BOOST-5213/[sdk]-allow-for-4byte-signatures-without-padding
=> [BOOST-5213] [SDK] allow for 4byte signatures without padding

.changeset/tame-bikes-run.md, packages/sdk/src/Actions/EventAction.ts
- makes the signatureType optional in the eventAction creation.
- derives the signatureType based on the signature used
https://linear.app/rh-app/issue/BOOST-5243/derive-signature-type-from-selector
=> [BOOST-5243] [SDK] derive signatureType from selector in eventAction

packages/evm/contracts/BoostCore.sol
Super simple fix so that we can support tokens that don't allow for transfers of amount zero (💩 )
💔 Thank you!
=> [BOOST-5217] feat(evm): only trigger dust hatch if there is a value amount

packages/evm/contracts/budgets/ManagedBudgetWithFees.sol, packages/evm/test/budgets/ManagedBudgetWithFees.t.sol
Now that we're supporting topups, this bug should be fixed, where we increment the maxFee by the disbursemd fee calculation instead of setting it for each individual deposit. This correctly accumulates the max fee payout for managers.
=> [BOOST-5240] fix(evm): increment management fee on disbursement rather than set it

packages/evm/contracts/budgets/AManagedBudgetWithFeesV2.sol, packages/evm/contracts/budgets/ManagedBudgetWithFeesV2.sol, packages/evm/test/budgets/ManagedBudgetWithFeesV2.t.sol
This iteration of managed budget tracks BoostCore deployments that the
budget targets over time, and allows managers to interact with
deprecated versions via overloaded functions. Since much of the security
model for boosts is contained in BoostCore, managers cannot access a
boost core deployment that was not already set by an admin.
management fee payouts on BoostCore against boosts not
deployed by a budget fail thanks to pre-existing logic that tracks
disbursements and stores the incentive address. If the incentive address
in the boost does not match that of the disbursement, it will fail, and replays against multiple BoostCore deployments will fail
=> [BOOST-5223] feat(evm): implement managed budget V2

packages/evm/contracts/BoostCore.sol, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/BoostCore.ts, packages/sdk/src/Incentives/AllowListIncentive.ts, packages/sdk/src/Incentives/CGDAIncentive.ts, packages/sdk/src/Incentives/ERC20Incentive.ts, packages/sdk/src/Incentives/ERC20PeggedIncentive.ts, packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.ts, packages/sdk/src/Incentives/PointsIncentive.ts
Ended up adding helpers to every incentive to compose the correct payload for the topup so we can just call into that with the topup amount. I'm still torn, I think using a `Transfer` struct over an `InitPayload` struct might be better since we wouldn't need to call into the incentive as heavily. It also may make sense to add some additional tests with the other incentives. I'm not sure if we still want to add a helper to the budgets as well - I'm leaning towards yes - but that still needs to be added if so.
=> [BOOST-5225] feat(sdk): add topup helpers to SDK

packages/evm/contracts/BoostCore.sol, packages/evm/contracts/budgets/ManagedBudgetWithFees.sol, packages/evm/contracts/incentives/ERC20Incentive.sol, packages/evm/contracts/incentives/ERC20PeggedIncentive.sol, packages/evm/contracts/incentives/ERC20PeggedVariableCriteriaIncentive.sol, packages/evm/contracts/incentives/ERC20VariableCriteriaIncentive.sol, packages/evm/contracts/incentives/ERC20VariableIncentive.sol, packages/evm/contracts/shared/IToppable.sol, packages/evm/hardhat_build.config.cjs, packages/evm/test/BoostCore.t.sol, packages/evm/test/budgets/ManagedBudgetWithFees.t.sol, packages/evm/test/incentives/ERC20Incentive.t.sol, packages/evm/test/incentives/ERC20PeggedIncentive.t.sol, packages/evm/test/incentives/ERC20PeggedVariableCriteriaIncentive.t.sol, packages/evm/test/incentives/ERC20VariableCriteriaIncentive.t.sol, packages/evm/test/incentives/ERC20VariableIncentive.t.sol, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/BoostCore.ts, packages/sdk/src/Incentives/AllowListIncentive.ts, packages/sdk/src/Incentives/CGDAIncentive.ts, packages/sdk/src/Incentives/ERC20Incentive.ts, packages/sdk/src/Incentives/ERC20PeggedIncentive.ts, packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.ts, packages/sdk/src/Incentives/PointsIncentive.ts
This PR introduces a new top-up flow in `BoostCore` that routes additional tokens into existing incentives, adding `topupIncentiveFromBudget` (for budget-based tokens) and `topupIncentiveFromSender` (for user-supplied tokens). Both flows gather all tokens in `BoostCore` , compute and record protocol fees, and temporarily approve the incentive contract to pull the remainder via its `topup` function. We remove approval after the transfers. Two things to watch out for in review are that funds can't be pulled out of core if there _was_ a malicious incentive and that all permissions on the budget are respected. Basically we want to avoid loss of funds.
**Assumptions**:  
- If sending directly the user has already approved `BoostCore` for ERC20 tokens or setApprovalForAll for ERC1155 tokens .
- …
=> [BOOST-5224] feat(evm): add topup functionality to core

.changeset/late-boxes-sell.md, packages/sdk/src/BoostCore.ts
Despite passing in an address to the BoostCore, it is strictly tied to the current deployed addresses.
This change allows using the BoostCore instance to previous deployments of BoostCore
=> [ADHOC] Allow overwrite of addresses in BoostCore

packages/sdk/src/BoostCore.ts
Accidentally removed the optional address. This fix makes it optional again
=> [ADHOC] hotfix(sdk): make address optional

packages/sdk/src/BoostCore.test.ts, packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts, packages/sdk/src/Incentives/PointsIncentive.ts
Adds testing for `ERC20PeggedVariableCriteriaIncentive` in the boost core tests to ensure full compatability. Also adds tests for topup functionality with that specific configuration into the boost core tests and fixes the encoding issue that was found during integration. I also looked over the other functions that prepare the topup payloads to check for payload size conflicts and fixed a similar issue in the point incentive even though we're not using it right now.
=> [ADHOC] test(sdk): ERC20PeggedVariableCriteriaIncentive core and topup testing

.changeset/chilled-walls-explode.md, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/BoostCore.ts
Tweaks the default behavior of `BoostCore` in order to use a `LimitedSignerValidator` with a max claim count of 1 in cases where no validator is supplied (should be the majority of boost creations). Also adds code so that the default HH account 0 is added as a signer validator if the chain is a local test chain and adds tests to the boost core test suite to ensure this max claim count is enforced. There may be a better approach to adding the signer to the default `LimitedSignerValidator` but this avoid the need to pipe around even the testnet PK. That pattern is for sure the most questionable part of this PR though so probably deserves the most attention.
=> [ADHOC] feat(sdk): boost core defaults to LimitedSignerValidator

.changeset/clean-parents-laugh.md, packages/sdk/src/Incentives/ERC20PeggedIncentive.ts, packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts, packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.test.ts, packages/sdk/src/Incentives/ERC20VariableIncentive.ts
- Updates the return type of `decodeClaimData` on `ERC20VariableIncentive` to return `Promise<bigint>` instead of `bigint`
- Adds `decodeClaimData` override for `ERC20VariableCriteriaIncentive`
=> [ADHOC] Decode Claim Data Update

.changeset/green-clouds-fly.md, packages/cli/src/commands/seed.ts, packages/evm/contracts/incentives/AERC20PeggedVariableCriteriaIncentive.sol, packages/evm/contracts/incentives/AERC20VariableCriteriaIncentive.sol, packages/evm/test/incentives/ERC20PeggedVariableCriteriaIncentive.t.sol, packages/evm/test/incentives/ERC20VariableCriteriaIncentive.t.sol, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/BoostCore.test.ts, packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.test.ts, packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts, packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.test.ts, packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.ts
Adds a `valueType` param to the incentiveCriteria for variable incentive types. This is necessary as we treat these values differently when calculating the reward values.
=> [BOOST-5352] add valueType to incentiveCriteria Struct

.changeset/red-beds-repair.md, packages/sdk/src/Actions/EventAction.test.ts, packages/sdk/src/Actions/EventAction.ts, packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentiveV2.ts, packages/sdk/src/Incentives/ERC20VariableCriteriaIncentiveV2.ts
- adds tuple support for incentive criteria in variable incentives
Unfortunately we only have 8-bits to work with on the criteria field index, so we treat the first 32 indexes as normal, and the rest (32-253) are available for packing the tuple parameters.
Due to this limitation, the tuple must be within the first 14 arg parameters, and the value we want to access must be an integer value within the first 14 parameters of the tuple.
=> [BOOST-5496] incentive criteria tuple support

.changeset/little-goats-vanish.md, packages/sdk/src/Actions/EventAction.ts
- returns the logs used to validate the actionSteps so they can be used to determine the Claimant and RewardScalar
- `getLogsFromActionSteps` borrows a lot of the logic from `validateActionSteps` . The main difference is that it returns the logs used to validate the actionSteps instead of a boolean. This allows us to retain backwards compatibility by leaving the existing validateActionSteps methods untouched.
- if logs are passed into `deriveActionClaimantFromTransaction`, we use those logs first, these will be the logs that we used to validate the action steps. If a claimant is not found off these logs, we continue with the existing logic.
=> [BOOST-5513] use actionSteps logs to determine claimant
