packages/sdk/package.json
packages/sdk/src/Auth/Auth.ts
packages/sdk/src/Auth/PassthroughAuth.test.ts
packages/sdk/src/Auth/PassthroughAuth.ts
packages/sdk/src/BoostCore.test.ts
packages/sdk/src/BoostCore.ts
packages/sdk/src/Deployable/Deployable.ts
packages/sdk/src/Deployable/DeployableTarget.ts
packages/sdk/src/index.test.ts
packages/sdk/src/index.ts

Implement passthrough auth integration in sdk, including tests

[BOOST-4599] feat(sdk): PassthroughAuth integration

---

packages/evm/contracts/incentives/APointsIncentive.sol
packages/evm/test/incentives/PointsIncentive.t.sol

- check if authorized to claim on the target points contract at time of claim
- unit test

[BOOST-4567] feat(evm): integrate points and pointsincentive auth schemes

---

package.json
packages/evm/contracts/BoostCore.sol
packages/evm/contracts/actions/AERC721MintAction.sol
packages/evm/contracts/actions/Action.sol
packages/evm/contracts/shared/BoostLib.sol
packages/evm/contracts/shared/IBoostClaim.sol
packages/evm/contracts/validators/ASignerValidator.sol
packages/evm/contracts/validators/AValidator.sol
packages/evm/contracts/validators/SignerValidator.sol
packages/evm/test/BoostCore.t.sol
packages/evm/test/actions/ERC721MintAction.t.sol
packages/evm/test/e2e/EndToEnd.t.sol
packages/evm/test/validators/SignerValidator.t.sol
packages/sdk/src/Incentives/AllowListIncentive.test.ts
packages/sdk/src/Incentives/CGDAIncentive.test.ts
packages/sdk/src/Incentives/ERC1155Incentive.test.ts
packages/sdk/src/Incentives/ERC20Incentive.test.ts
packages/sdk/src/Incentives/PointsIncentive.test.ts
packages/sdk/src/Validators/SignerValidator.test.ts
packages/sdk/src/Validators/SignerValidator.ts
packages/sdk/src/Validators/Validator.ts
packages/sdk/src/utils.ts
packages/sdk/test/helpers.ts
pnpm-lock.yaml

[BOOST-4562] feat(sdk): add interface and utils to support signing in SDK

---

packages/evm/contracts/actions/AEventAction.sol
packages/evm/contracts/actions/EventAction.sol
packages/evm/test/actions/EventAction.t.sol
packages/sdk/src/Actions/EventAction.ts
packages/sdk/src/utils.ts

- add `actionClaimant` to EventAction.InitPayload
- add getter
- add SDK support

[BOOST-4657] feat(evm): add claimant info to EventAction

---

packages/evm/test/budgets/ManagedBudget.t.sol

Coverage up to 96%.
Uncovered lines are the same as SimpleBudget. (Unsupported Asset Types) and the reconcile function.

[BOOST-4612]: test(evm): Increase ManagedBudget Coverage

---

packages/sdk/src/Incentives/ERC20VariableIncentive.ts

Corrects some of the comments in the sdk docs
💔 Thank you!

[ADHOC] update `ERC20VariableIncentive` sdk docs

---

packages/sdk/src/Actions/EventAction.test.ts
packages/sdk/src/Actions/EventAction.ts
packages/sdk/src/errors.ts

Adds tests and function helpers for validating function based Event Action steps.
💔 Thank you!

[BOOST-4746] feat(sdk): add function handling to eventaction validation

---

.github/actions/install-dependencies/action.yml
examples/next/package.json
package.json
pnpm-lock.yaml

This is mostly just to stay in sync with our other repos

[ADHOC] Update pnpm to 9.4.0

---

examples/ens-register/hardhat.config.cjs
packages/sdk/hardhat.config.cjs

- test was failing for ENS. Removing the forking property fixes the issue.
- ~~adjusted hardhat config in sdk package so default chain is 31337. Tests were previously failing.~~ This is fixed in #167

[ADHOC] update hardhat config in ENS example

---

packages/evm/script/solidity/Deploy_Modules.s.sol
packages/evm/script/solidity/Util.s.sol

This should make boost creations that don't involve an allow list
marginally cheaper and simplify troubleshooting by minimizing moving
parts in many cases.

[BOOST-4777] feat(evm): implement OpenAllowList predeploy

---

.changeset/nasty-windows-mate.md
packages/sdk/src/Actions/EventAction.ts
packages/signatures/manifests/functions.json

add `mint(address,uint256,address,uint256,address,string)` signature
merge knownSignature parameter with our signatures registry for less failure potential when looking up event/function selectors
💔 Thank you!

[ADHOC] feat(sdk): merge knownsignatures with our registry

---

packages/evm/contracts/BoostCore.sol
packages/evm/contracts/budgets/ABudget.sol
packages/evm/contracts/budgets/AManagedBudget.sol
packages/evm/contracts/budgets/ManagedBudget.sol
packages/evm/contracts/budgets/VestingBudget.sol
packages/evm/contracts/incentives/ACGDAIncentive.sol
packages/evm/contracts/incentives/AERC1155Incentive.sol
packages/evm/contracts/incentives/AERC20Incentive.sol
packages/evm/contracts/incentives/AERC20VariableIncentive.sol
packages/evm/contracts/incentives/AIncentive.sol
packages/evm/contracts/incentives/AllowListIncentive.sol
packages/evm/contracts/incentives/CGDAIncentive.sol
packages/evm/contracts/incentives/ERC1155Incentive.sol
packages/evm/contracts/incentives/ERC20Incentive.sol
packages/evm/contracts/incentives/ERC20VariableIncentive.sol
packages/evm/contracts/incentives/PointsIncentive.sol
packages/evm/contracts/shared/IClaw.sol
packages/evm/test/BoostCore.t.sol
packages/evm/test/budgets/ManagedBudget.t.sol
packages/evm/test/budgets/VestingBudget.t.sol

This accounts for a bug reported by @JamieLottering  that was handling the disbural accounting incorrectly.
Before we were increasing disbursal in an internal helper, in reality it should be incremented on disbursal and decremented on recovery.
💔 Thank you!

[BOOST-4829] feat(evm): tweak managed budget disbursal tracking

---

packages/evm/script/solidity/Deploy.s.sol
packages/evm/script/solidity/Deploy_Modules.s.sol

It is helpful to know which address is broadcasting transacitons
from scripts
Bacon ipsum dolor amet sirloin flank tenderloin, frankfurter drumstick t-bone pastrami leberkas shank beef cupim. Pork loin filet mignon corned beef pork leberkas meatloaf boudin frankfurter bresaola picanha venison tenderloin tail ball tip t-bone. Venison prosciutto pancetta fatback tenderloin chicken. T-bone cow spare ribs doner, turkey prosciutto capicola porchetta boudin pork chop rump chicken picanha venison beef ribs. Sausage short loin ham hock fatback burgdoggen pork loin. Filet mignon short loin venison meatloaf pork chop frankfurter beef ham flank chuck pancetta leberkas ball tip porchetta capicola. Kevin flank brisket, biltong alcatra prosciutto sirloin bacon drumstick salami.

[adhoc] chore(evm): log deployer address during script execution

---

packages/evm/contracts/incentives/ERC20Incentive.sol
packages/evm/test/BoostCore.t.sol
packages/evm/test/incentives/ERC20Incentive.t.sol
packages/sdk/src/Incentives/ERC20Incentive.ts

Modifies the permissions for the ERC20Incentive so that drawing raffles will work
💔 Thank you!

[ADHOC] feat: add manager back to erc20 incentive for raffle

---

.changeset/config.json
.changeset/curly-rice-cough.md
examples/agora-vote/src/agora-vote.test.ts
examples/delegate-action/src/delegate-action.test.ts
examples/ens-register/src/ens-register.test.ts
examples/swap-specific-dex/src/swap-specific-dex.test.ts
examples/zora-mint/src/zora-mint.test.ts
packages/sdk/src/Actions/EventAction.test.ts
packages/sdk/src/Actions/EventAction.ts
packages/sdk/vitest.config.ts
pnpm-lock.yaml
test/package.json
test/src/allKnownSignatures.ts

make `ValidationStepParams.knownSignatures` mandatory, remove dependency on @boostxyz/signatures from @boostxyz/sdk
also don't publish signatures and sdk together
💔 Thank you!

[ADHOC] feat(sdk): mandatory knownSignatures for validation

---

.changeset/clean-suits-tie.md
packages/signatures/manifests/events.json
packages/signatures/manifests/functions.json

- adds function signature for `buy1155` from zora.
- adds function signature for `mintTo` from sound.
- add event signature for `ZoraTimedSaleStrategyRewards` from zora.
- adds event signatures for `Minted` from sound.
💔 Thank you!

[ADHOC]: add signatures for sound and zora

---

.changeset/fluffy-foxes-joke.md
packages/sdk/src/Actions/EventAction.ts

[ADHOC] fix(sdk,EventAction): must specify chainId during validation to cover all conditional cases

---

.changeset/chilly-pets-live.md
packages/sdk/src/Actions/EventAction.ts
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.test.ts
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.ts
packages/sdk/src/utils.ts

Similar to the other cheat codes we're using, uses max uint8 to indicate gas rebate for a variable criteria incentive.
💔 Thank you!

[BOOST-4842] feat(sdk): add gas used setting for variable incentives sdk helpers

---

.changeset/tender-crabs-sniff.md
packages/sdk/package.json
packages/sdk/src/BoostCore.ts
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.test.ts
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.ts
packages/sdk/src/Incentives/ERC20VariableIncentive.ts
packages/sdk/src/Incentives/Incentive.ts
pnpm-lock.yaml

- make erc20variablecriteria extend erc20variable to fix #229 
- remove erc20variablecriteria dependence on signatures like eventaction
- fix some jsdocs
- fix missing abi export
- fix missing package exports
💔 Thank you!

refactor(sdk): erc20variablecriteria extends erc20variable, remove dependence on signatures

---

packages/evm/contracts/incentives/AERC20VariableCriteriaIncentive.sol
packages/evm/contracts/incentives/ERC20VariableCriteriaIncentive.sol
packages/evm/script/solidity/ComponentInterface.s.sol
packages/evm/test/incentives/ERC20VariableCriteriaIncentive.t.sol
packages/sdk/src/Actions/EventAction.test.ts
packages/sdk/src/Incentives/Incentive.ts

Adds the correct component interface and related helpers for critieria incentives.
💔 Thank you!

[ADHOC] chore: add component interface for variable critieria incentive

---

packages/evm/contracts/BoostCore.sol

Super small cleanup refactor based on auditor feedback
💔 Thank you!

[ADHOC] refactor(evm): remove unused bytes data in add incentive

---

packages/evm/test/validators/SignerValidator.t.sol

We are not cutting off the upper half of the curve, so it's technically
feasible to submit a modified signature that will pass validation with
`ecrecover`. However, other measures and validations ensure that this
doesn't amount to a security risk. First, eip-712 ensures that the
signature cannot be replayed across chains. Second, we are not storing
signatures as keys anywhere and instead use the hash payloads, rendering
signature replay on the same chain impossible.
The _only_ risk involving signautures entails approving a boost claim
with multiple incentives before the claimant is eligible to claim all
incentives, since we sign off on incentive quantity instead of individual
incentives. However, this would be an issue regardless of whether or not
the signature was malleable.

test(evm): create test for signature malleability

---

packages/evm/contracts/incentives/AERC20VariableCriteriaIncentive.sol
packages/evm/contracts/incentives/ERC20VariableCriteriaIncentive.sol
packages/evm/contracts/incentives/ERC20VariableIncentive.sol
packages/evm/test/incentives/ERC20VariableCriteriaIncentive.t.sol
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.test.ts
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.ts

We enforce on chain a maximum reward per chain. Also includes protocol and SDK test updates.
💔 Thank you!

[BOOST-4877] feat support max rewards in variable criteria incentives

---

packages/sdk/src/BoostCore.ts
packages/sdk/src/utils.ts

Please describe your pull request
💔 Thank you!

[ADHOC][DONT MIND ME] chore: general cleanup i'm adding to gradually

---

packages/evm/contracts/incentives/ERC20VariableCriteriaIncentive.sol
packages/evm/contracts/incentives/ERC20VariableIncentive.sol
packages/evm/test/incentives/ERC20VariableCriteriaIncentive.t.sol

Added claim increment on the variable incentives
💔 Thank you!

[ADHOC] fix(evm): update claims on claim

---

packages/evm/contracts/BoostCore.sol
packages/evm/contracts/incentives/ERC20VariableCriteriaIncentive.sol

Renames a mapping in core to be more clear and tweaks a bug in RBAC for ERC20VariableCriteriaIncentives
💔 Thank you!

[ADHOC] chore: final protocol tweaks

---

.changeset/fair-ravens-share.md
packages/sdk/src/BoostCore.ts
packages/sdk/src/Budgets/ManagedBudget.test.ts
packages/sdk/src/Budgets/ManagedBudget.ts
packages/sdk/src/Incentives/CGDAIncentive.test.ts
packages/sdk/src/Incentives/CGDAIncentive.ts
packages/sdk/src/Incentives/ERC20Incentive.test.ts
packages/sdk/src/Incentives/ERC20Incentive.ts
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.test.ts
packages/sdk/src/Incentives/ERC20VariableIncentive.test.ts
packages/sdk/src/Incentives/ERC20VariableIncentive.ts
packages/sdk/src/errors.ts
test/src/MockERC20.ts

- add clawbackFromTarget API, docs, tests
💔 Thank you!

[ADHOC] feat(sdk): clawbackFromTarget API for ManagedBudget

---

.changeset/afraid-papayas-kiss.md
packages/sdk/src/BoostCore.test.ts
packages/sdk/src/BoostCore.ts
packages/sdk/src/BoostRegistry.test.ts
packages/sdk/src/Incentives/CGDAIncentive.ts
packages/sdk/src/Incentives/ERC20Incentive.test.ts
packages/sdk/src/Incentives/ERC20Incentive.ts
packages/sdk/src/Incentives/ERC20VariableIncentive.test.ts
packages/sdk/src/Incentives/ERC20VariableIncentive.ts
packages/sdk/src/claiming.ts
packages/sdk/src/index.test.ts
packages/sdk/src/utils.ts

- add `calculateProtocolFee` API to boost core
- add `getTotalBudget` API to erc20 incentives
- use them together, wow
💔 Thank you!

[ADHOC] feat(sdk): add api to calculate protocol fees

---

.changeset/new-dodos-join.md
packages/evm/contracts/BoostCore.sol

We weren't attributing the correct destination for the protocol fees previously
💔 Thank you!

[ADHOC] refactor(evm): change attribution for clawback event in core

---

packages/evm/contracts/budgets/AManagedBudgetWithFees.sol
packages/evm/contracts/budgets/ManagedBudget.sol
packages/evm/contracts/budgets/ManagedBudgetWithFees.sol
packages/evm/contracts/incentives/AERC20Incentive.sol
packages/evm/contracts/incentives/AERC20VariableIncentive.sol
packages/evm/contracts/incentives/AIncentive.sol
packages/evm/contracts/incentives/AllowListIncentive.sol
packages/evm/contracts/incentives/CGDAIncentive.sol
packages/evm/contracts/incentives/ERC1155Incentive.sol
packages/evm/contracts/incentives/ERC20Incentive.sol
packages/evm/contracts/incentives/ERC20VariableIncentive.sol
packages/evm/contracts/incentives/PointsIncentive.sol
packages/evm/contracts/shared/BoostError.sol
packages/evm/script/solidity/ComponentInterface.s.sol
packages/evm/script/solidity/Deploy_Modules.s.sol
packages/evm/script/solidity/Util.s.sol
packages/evm/test/BoostCore.t.sol
packages/evm/test/budgets/ManagedBudgetWithFees.t.sol

This could still probably use more test coverage but the core logic is fuzzed.
Failure cases and invalid paths still need to be covered, just looking for a
check on the implementation right now.

[BOOST-4839] feat(evm): implement Managed Budget with Fees

---

packages/evm/contracts/actions/EventAction.sol
packages/evm/contracts/incentives/CGDAIncentive.sol
packages/evm/contracts/incentives/ERC1155Incentive.sol
packages/evm/contracts/incentives/ERC20Incentive.sol
packages/evm/contracts/incentives/ERC20VariableCriteriaIncentive.sol
packages/evm/contracts/incentives/ERC20VariableIncentive.sol
packages/evm/contracts/incentives/PointsIncentive.sol
packages/evm/contracts/validators/SignerValidator.sol

adds events into all of our module init calls as per request for dune dashboards.
💔 Thank you!

[BOOST-5061] feat(evm): add events to modules

---

.changeset/hot-points-begin.md

ITS JUST A CHANGESET
💔 Thank you!

chore: add changeset for deployment

---

packages/evm/contracts/BoostCore.sol
packages/evm/contracts/shared/IProtocolFeeModule.sol
packages/evm/contracts/shared/Mocks.sol
packages/evm/test/BoostCore.t.sol

This change sets us up to take protocol fees in a different token than the boosts reward in the future with changes to the protocol fee module.
💔 Thank you!

[ADHOC] feat(evm): add protocol fee asset to the protocol fee module

---

packages/evm/contracts/BoostCore.sol
packages/evm/test/BoostCore.t.sol

If residual token amounts accumulate due to integer division, this helper
will transfer those amounts to the protocol fee recipient inline during
a claim protocol fee settlement.
💔 Thank you!

[ADHOC] chore(evm): sweep the dust in boost core

---

packages/evm/contracts/incentives/ERC20PeggedVariableCriteriaIncentive.sol
packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.test.ts
packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts
packages/sdk/src/Incentives/Incentive.ts
test/src/helpers.ts

- adds tests and fixes for Erc20PeggedVariableIncentive
This PR bases off #326

[ADHOC]: add tests and fixes for pegged variable incentives

---

.changeset/sixty-mirrors-wink.md
packages/sdk/src/Actions/EventAction.ts
packages/sdk/src/utils.ts

- adds specific logic during actionStep validation to deal with the `Transfer` event collision.

[BOOST-5113] add specific logic for transfer event log decoding

---

.github/actions/install-dependencies/action.yml
package.json

- bumps pnpm version to 9.15.0 to be consistent with other boostxyz repos

[ADHOC] chore: update pnpm version to 9.15.0

---

.changeset/sixty-windows-yell.md
packages/sdk/src/Incentives/ERC20PeggedIncentive.ts
packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts

- updates bases for pegged incentive types

[ADHOC] update pegged incentive bases

---

.changeset/calm-numbers-add.md
packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts

- adds decode method to ERC20PeggedVariableCriteriaIncentive
Needed for back-end to decode amount from claim data https://github.com/boostxyz/boost/blob/17ce3dae22d8423ef1ddc04cfe64894e59e76e10/apps/backend/src/utils/incentives.ts#L230-L235

[ADHOC] add decode method to pegged variable incentive

---

.changeset/khaki-squids-compare.md
packages/signatures/manifests/events.json

- add Wow contract events (WowTokenBuy, WowTokenSell, WowTokenTransfer, WowTokenFees, CoopTokenTransfer)

[ADHOC] add wow event signatures

---

.changeset/wild-rings-itch.md
packages/sdk/src/BoostCore.test.ts
packages/sdk/src/BoostCore.ts

This PR has a `createBoostRaw` function to help with loading states

[ADHOC] Add createBoostRaw function

---

packages/sdk/src/errors.ts

[ADHOC] fix typo in BoostNotFoundError

---

.changeset/cyan-jokes-play.md
packages/sdk/src/BoostCore.ts

Reverts changes made in https://github.com/boostxyz/boost-protocol/pull/396 and  https://github.com/boostxyz/boost-protocol/pull/398

[ADHOC] Revert #396 & #398

---

.changeset/real-trainers-compete.md
packages/sdk/src/Validators/LimitedSignerValidator.ts

Replace `SignerValidator` with `LimitedSignerValidator`

[ADHOC] fix(sdk): use LimitedSignerValidator base

---

.changeset/tough-actors-cross.md
packages/evm/script/solidity/ComponentInterface.s.sol
packages/sdk/src/Validators/Validator.ts

Generate the interface for LimitedSignerValidator so that it can be used within the sdk

[ADHOC] Add limited signer valiator interface

---

.changeset/seven-ducks-invite.md
packages/sdk/src/Validators/LimitedSignerValidator.ts

- updates format of privateKey used for signing typed data

[ADHOC] sign typedData using signer.privateKey

---

.changeset/warm-cycles-care.md
packages/cli/package.json
packages/cli/src/cli.ts
packages/cli/src/commands/deploy.ts
packages/cli/src/commands/seed.ts
packages/cli/src/utils.ts
packages/evm/contracts/shared/Mocks.sol
pnpm-workspace.yaml
test/src/MockERC1155.ts
test/src/MockERC721.ts
test/src/helpers.ts
test/src/viem.ts
turbo.json

This PR generates types for the cli package on release and cleans up a bunch
of the typing so the types are exportable

[ADHOC] chore(cli): create types for cli package release

---

.changeset/cool-spiders-notice.md
packages/evm/contracts/incentives/AERC20PeggedVariableCriteriaIncentive.sol
packages/evm/contracts/incentives/AERC20VariableCriteriaIncentive.sol
packages/evm/contracts/incentives/ERC20PeggedVariableCriteriaIncentive.sol
packages/evm/contracts/incentives/ERC20VariableCriteriaIncentive.sol
packages/evm/script/solidity/ComponentInterface.s.sol
packages/sdk/package.json
packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentive.ts
packages/sdk/src/Incentives/ERC20PeggedVariableCriteriaIncentiveV2.test.ts
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentive.ts
packages/sdk/src/Incentives/ERC20VariableCriteriaIncentiveV2.test.ts
packages/sdk/src/Incentives/Incentive.ts
packages/sdk/src/index.ts

readd original v1 variable criteria contracts and sdk implementations
patch bump for canary.1
💔 Thank you!

[ADHOC] chore(evm,sdk): re-add v1 incentive criteria

---

.changeset/fifty-cougars-melt.md
packages/sdk/src/Actions/EventAction.ts

- returns the first matching claimant instead of the last

[ADHOC]: return first matching addressCandidate

---

package.json
pnpm-lock.yaml

- fixes an issue with hardhat node failing to start as outlined in [this github issue.](https://github.com/NomicFoundation/hardhat/issues/5816) This is causing the use-case tests to fail.

[ADHOC] update hardhat version to 2.24.0
